### ISSUE TITLE
Screenshots include the video player's overlay shading

### ISSUE THREAD

**Issue by XT3RM1N8R** [FutureMillennium/Screenshot-YouTube#10]
When the player overlay is displayed, screenshots include the shading from the player overlay at the top and bottom of images.
This distorts these areas of screenshots and makes for improper screenshots.
I am assuming that this is a bug and I will gladly reformat this issue if I need to.
Thanks!
![image](https://user-images.githubusercontent.com/22762993/87104789-94d4c180-c21e-11ea-9a36-189562101b6b.png)

**Comment by FutureMillennium** [comment]
Hi, I doubt it. You're looking at what's in the video. Youtube has no such overlay that I know of, and the extension takes a screenshot of the video element directly, nothing else on the page affects it.

Can you provide a screenshot of the overlay you speak of and the URL of the video?

**Comment by XT3RM1N8R** [comment]
Upon further review, this is actually not a bug with Screenshot-YouTube; it is actually an aspect of the video as you have stated.
Here is the video URL, as requested: https://youtu.be/XsfwAxYcAZw
**Screenshot-YouTube appears to be working as intended.**

---

Regarding the misunderstanding, it would appear that my testing was flawed, as the several screenshots that I took all happened to be at times that this vignette was in the video; however, when I inspected the video, I had done so at times where the vignette coincidentally disappeared.

Regarding my comments about the YouTube "overlay", I am referring to an overlay that is present in the YouTube player fullscreen view and in the YouTube player embed view.
The vignette on the overlay is not as noticeable as it used to be, yet it was a problem for me in the past when I explored solutions similar to Screenshot-YouTube.
Previous solutions would sometimes remove the controls and text, but not the vignette.
I have simply mistaken the embedded vignette of the original video as a problem that I recognize from the past.

---

I will include an example so that you may better understand what I mean.
Let's consider this video of _**White Screen**_: https://youtu.be/QggJzZdIYPI
## Normal Fullscreen View - With Overlay
![image](https://user-images.githubusercontent.com/22762993/87997001-848fd280-cab9-11ea-851e-9dca02a50b7b.png)

## Fullscreen View - Only Vignette
![image](https://user-images.githubusercontent.com/22762993/87997200-054ece80-caba-11ea-85ec-c558f7186269.png)

This is the behavior seen with the YouTube player at the time of this posting.
I mistakenly wrote off the vignette in the original video as a replication of this concept via a bug in Screenshot-YouTube.

I appreciate your patience and quick response--and of course, your work on Screenshot-YouTube!
Thanks!

**Comment by FutureMillennium** [comment]
No worries. And yes – I was referring to how the screenshot overlay has sharp edges, which the YouTube one does not have.
