### ISSUE TITLE
Feature request: Option to save as JPEG

### ISSUE THREAD

**Issue by rjmunro** [FutureMillennium/Screenshot-YouTube#12]
For most video frames, saving as a JPEG will produce a lot smaller file (about 1/10th the size) for a negligible loss in quality, especially compared to the quality already lost in the video itself. This would make the files much easier to email around etc.

This is a really great plugin by the way :-)

**Comment by FutureMillennium** [comment]
Added in version 2.4.0. Thanks @Zertsu!
