### ISSUE TITLE
Put the timestamp in the frame filename

### ISSUE THREAD

**Issue by rjmunro** [FutureMillennium/Screenshot-YouTube#13]
We use this plugin to review our videos and email comments about shots and stuff. It would be great if we could press the screenshot button while the video is playing, then afterwards be able to see exactly where in the video each capture came from - the easiest way to do this would be to put the timestamp in the filename.

**Comment by FutureMillennium** [comment]
The timestamp is in the screenshot filename since version 2.1.0, 2018-07-08.
