### ISSUE TITLE
As of oktober 11 file name broke (_0-1 screenshot.png)

### ISSUE THREAD

**Issue by Defusr** [FutureMillennium/Screenshot-YouTube#16]
As of oktober 11 2021 the screenshot file name is broken.
The youtube video name is missing from the screenshot file name.
Example now: _0-1 screenshot.png
Example past: Privilege 580 Video Walkthrough w_ Commentary 9-8 screenshot.png
![Schermafbeelding 2021-10-13 192621](https://user-images.githubusercontent.com/87338233/137184293-d5d0263a-f8c9-4681-8f0b-61bb4bcb99f2.png)

**Comment by icesou** [comment]
ya me too
plz fix it
