### ISSUE TITLE
Chome manifest MV3 conversion?

### ISSUE THREAD

**Issue by djpecot** [FutureMillennium/Screenshot-YouTube#21]
Is there any plan to bump to MV3? [MV2 will be going offline soon..](https://developer.chrome.com/docs/extensions/mv3/mv2-sunset/
)

**Comment by KoolKeith** [comment]
For some reason it still works today (Late June 2023).
But please, Mister Future Millenium, update to V3 !
You created the only honorable Extension like this, which is open source.

I personally take your Extension and add two functionalities: 
1. Add a graphical "info banner" to the canvas, which is burned in.
2. Sanitize the future filename to have less toxic characters.

I can send you my mods, if you want to get an inspiration !

But all of this has no future with V2 :(


![20 Minutes Of Interesting Animal Moments Caught On Camera- 11-24 screenshot](https://github.com/FutureMillennium/Screenshot-YouTube/assets/10271212/3e02a9e5-55a3-494f-9493-b134fb50a6f9)

**Comment by FutureMillennium** [comment]
Moved to manifest v3 in version 3.0.0.
