### ISSUE TITLE
Direct download bypassing "Save As" window.

### ISSUE THREAD

**Issue by anandinasu** [FutureMillennium/Screenshot-YouTube#3]
If I remember correctly, in the previous version there was an option to directly download the screenshot bypassing the "Save As" windows and I can't find that option in the new version. I am not sure whether this is a bug or change in YouTube policy or you decided to remove that feature. If you decided to remove the feature, is it possible to bring it back or give access to the previous version of the extension? Thanks a lot for this fantastic extension. It is very very useful in my studies.

**Comment by FutureMillennium** [comment]
Hi, clicking on the “Screenshot” button always downloads the screenshot immediately. There is no “Save as” dialog, and it's never been an option.

If you are getting the “Save as” dialog, all I can think of is a change in Chrome, or a different extension interfering. Try disabling other extensions, or only enabling this extension in an anonymous window and trying it there.

What's the Chrome version you're running?
