### ISSUE TITLE
[Chrome] Screenshot button no longer shows up

### ISSUE THREAD

**Issue by TLiley2** [FutureMillennium/Screenshot-YouTube#30]
For some reason the screenshot button no loner shows up

Extension Version: v2.4.1
Browser Name: Chrome
Browser Version: v119.0.6045.160

**Comment by chenjr0719** [comment]
Same issue after switch to graphics backend to default which is D3D11 on Windows. Switch back to OpenGL can fix this issue.

**Comment by luongson86** [comment]
> For some reason the screenshot button no loner shows up
> 
> Extension Version: v2.4.1 Browser Name: Chrome Browser Version: v119.0.6045.160

Same for me! but shortcut still work
Extension Version: v2.4.1
Browser Name: Chrome for Linux
Browser Version: 120.0.6099.224 (Official Build) (64-bit)

**Comment by macgile** [comment]
Hi,

It cannot display the button because the AddScreenshotButton() function is called before loading the button bar: document.getElementsByClassName("ytp-right-controls")[0]
The button cannot be inserted because document.getElementsByClassName("ytp-right-controls")[0] return "indefined"

**Comment by FutureMillennium** [comment]
This should hopefully no longer be an issue in version 3.0.0.
