### ISSUE TITLE
Extension requires permission to read browsing history

### ISSUE THREAD

**Issue by danieljbk** [FutureMillennium/Screenshot-YouTube#34]
![screenshot](https://github.com/FutureMillennium/Screenshot-YouTube/assets/79312811/57548810-2e0b-4bba-a231-1020a13d6461) 

This is a screenshot of permissions stated as required when installing extension from Chrome store.

Why does it state the extension can view the user's browsing history? Such a permission doesn't seem to be in the code.

And, I don't initially see a reason this extension would need to read the user's browsing history.

So...
1. Either this is a bug, 
2. I didn't find where that permission is located in the code, or
3. The code in this repo is different from the code of the actual extension.

**Comment by danieljbk** [comment]
![CleanShot 2024-05-17 at 11 37 19@2x](https://github.com/FutureMillennium/Screenshot-YouTube/assets/79312811/937b2dd4-3119-425b-b68e-0a366a1b8b13)

Manually installing the extension with this repo also required this permission. So the answer was #2, I didn't locate that permission in the code.

However, the question remains why this permission is required. It shouldn't be, intuitively.

I will assume it is a bug and leave this issue open, but I'm aware that it may be a workaround or something of that sort.

**Comment by FutureMillennium** [comment]
It watches history on youtube.com to add the Screenshot button and others, because Youtube rewrites history instead of doing a page load/reload when you i.e. click on a video. https://github.com/FutureMillennium/Screenshot-YouTube/blob/master/extension/background.js
There's probably a better solution…

**Comment by FutureMillennium** [comment]
Removed the permission in version 3.0.0.
