### ISSUE TITLE
This plugin not working on live video 

### ISSUE THREAD

**Issue by janurag** [FutureMillennium/Screenshot-YouTube#7]
Hello there,
I tried taking screenshot on the live video but it didn't work
https://www.youtube.com/watch?v=EEIk7gwjgIM

**Comment by FutureMillennium** [comment]
Works fine for me. Try refreshing the page and let me know.
![image](https://user-images.githubusercontent.com/7760353/74234258-b744cc00-4ccc-11ea-9b09-600653fbc4ae.png)

**Comment by janurag** [comment]
Yes, apparently i had to restart my chrome
