### ISSUE TITLE
screenshot is creating blank captures 

### ISSUE THREAD

**Issue by piratecinema** [FutureMillennium/Screenshot-YouTube#9]
All of the screenshots that I make are blank, clear PNGs
![Dirty Rotten Scoundrels 1-9-51 screenshot](https://user-images.githubusercontent.com/13894459/82182924-b06cbd00-98aa-11ea-9d39-f6f32fcf2120.png)
![Missy Elliott - Pass That Dutch  Official Music Video  4-0 screenshot](https://user-images.githubusercontent.com/13894459/82182946-b8c4f800-98aa-11ea-9683-c5002fe2c44c.png)

Yesterday, it worked. I tested this on a windows and a mac device.

**Comment by FutureMillennium** [comment]
Can you check if there are any errors in the console? I don't have the problem on my end

**Comment by piratecinema** [comment]
I just tested it again, it works. This is a great app.
